=== ardisragen/ocf/src/egeni/sfa/rspec.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://yuba.stanford.edu/egeni/rspec" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://yuba.stanford.edu/egeni/rspec">



    <complexType name="interfaceInfo">
    	<sequence>
    		<element name="port" type="int"></element>
    		<sequence maxOccurs="unbounded" minOccurs="0">
    			<element name="remoteNodeId" type="string"></element>
    			<element name="remotePort" type="int"></element>
    		</sequence>

    		<element name="flowSpaceEntry" type="tns:flowSpaceInfo"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="bandwidth" type="float" maxOccurs="1" minOccurs="0"></element>
    		<element name="latency" type="float" maxOccurs="1" minOccurs="0"></element>
    		<element name="lossRate" type="float" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <complexType name="flowSpaceInfo">
    	<sequence>
    		<element name="policy">
    			<simpleType>
    				<restriction base="string">
    					<enumeration value="readonly"></enumeration>
    					<enumeration value="allow"></enumeration>
    					<enumeration value="deny"></enumeration>
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="dl_src" maxOccurs="1" minOccurs="0">
            	<simpleType>
            		<restriction base="hexBinary">
            			<length value="6"></length>
            		</restriction>
            	</simpleType>
            </element>
            <element name="dl_dst" maxOccurs="1" minOccurs="0">
            	<simpleType>
            		<restriction base="hexBinary">
            			<length value="6"></length>
            		</restriction>
            	</simpleType>
            </element>
            <element name="dl_type" type="int" maxOccurs="1" minOccurs="0"></element>
    		<element name="vlan_id" type="int" maxOccurs="1" minOccurs="0"></element>
    		<element name="ip_src" maxOccurs="1" minOccurs="0">
    			<simpleType>
    				<restriction base="hexBinary">
    					<length value="4"></length>
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="ip_dst" maxOccurs="1" minOccurs="0">
    			<simpleType>
    				<restriction base="hexBinary">
    					<length value="4"></length>
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="ip_proto" type="int" maxOccurs="1" minOccurs="0"></element>
    		<element name="tp_src" type="int" maxOccurs="1" minOccurs="0"></element>
    		<element name="tp_dst" type="int" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>


    <element name="RSpec" type="tns:rspec"></element>
    
    <complexType name="rspec">
    	<sequence>
    		<element name="version" type="string"></element>
    		<element name="switchEntry" type="tns:switchInfo"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="hostEntry" type="tns:hostInfo"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="remoteNodeEntry" type="tns:remoteNodeInfo"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="flowSpaceEntry" type="tns:flowSpaceInfo" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <complexType name="nodeInfo">
    	<sequence>
    		<element name="nodeId" type="string"></element>
    		<element name="type" type="int" maxOccurs="1" minOccurs="0"></element>
    		<element name="interfaceEntry" type="tns:interfaceInfo"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="switchInfo">
    	<sequence>
    		<element name="node" type="tns:nodeInfo"></element>
    		<element name="switchFeatures" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="controllerUrl" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <complexType name="hostInfo">
    	<sequence>
    		<element name="node" type="tns:nodeInfo"></element>
    		<element name="cpuUtil" type="float" maxOccurs="1" minOccurs="0"></element>
    		<element name="memUtil" type="float" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>



    <complexType name="remoteNodeInfo">
    	<sequence>
            <element name="remoteURL" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="remoteType" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="node" type="tns:nodeInfo"></element>
        </sequence>
    </complexType>
</schema>

=== ardisragen/ocf/src/egeni/geniLight/rspec-sample-June2009.xml.REMOTE.518.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<tns:RSpec xmlns:tns="http://yuba.stanford.edu/geniLight/rspec" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://yuba.stanford.edu/geniLight/rspec http://yuba.stanford.edu/geniLight/rspec.xsd">

  <tns:version>1.0</tns:version>

  <tns:switchEntry>
    <tns:node>
      <tns:nodeId>640021f7cae400</tns:nodeId>
      <tns:interfaceEntry>
        <tns:port>26</tns:port>
        <tns:remoteNodeId>213109</tns:remoteNodeId>
        <tns:remotePort>38</tns:remotePort>
        <tns:remoteNodeId>134a34</tns:remoteNodeId>
        <tns:remotePort>2</tns:remotePort>
      </tns:interfaceEntry>
      <tns:interfaceEntry>
        <tns:port>28</tns:port>
      </tns:interfaceEntry>
      <tns:flowSpaceEntry>
      	<tns:policy>0</tns:policy>
      	<tns:port>32</tns:port>
      	<tns:dl_type>2</tns:dl_type>
      	<tns:tp_dst>423</tns:tp_dst>
      </tns:flowSpaceEntry>
      <tns:flowSpaceEntry>
      	<tns:policy>0</tns:policy>
      	<tns:port>1232</tns:port>
      	<tns:dl_dst>122</tns:dl_dst>
      	<tns:tp_src>4233</tns:tp_src>
      </tns:flowSpaceEntry>
    </tns:node>
  </tns:switchEntry>

  <tns:switchEntry>
    <tns:node>
      <tns:nodeId>2580021f7cae400</tns:nodeId>
      <tns:interfaceEntry>
        <tns:port>46</tns:port>
      </tns:interfaceEntry>
      <tns:interfaceEntry>
        <tns:port>48</tns:port>
      </tns:interfaceEntry>
    </tns:node>
  </tns:switchEntry>

  <tns:switchEntry>
    <tns:node>
      <tns:nodeId>1f40021f7cae400</tns:nodeId>
      <tns:interfaceEntry>
        <tns:port>41</tns:port>
      </tns:interfaceEntry>
      <tns:interfaceEntry>
        <tns:port>43</tns:port>
      </tns:interfaceEntry>
      <tns:interfaceEntry>
        <tns:port>44</tns:port>
      </tns:interfaceEntry>
    </tns:node>
  </tns:switchEntry>

  <tns:switchEntry>
    <tns:node>
      <tns:nodeId>1900021f7cae400</tns:nodeId>
    </tns:node>
  </tns:switchEntry>

  <tns:switchEntry>
    <tns:node>
      <tns:nodeId>12c0021f7cae400</tns:nodeId>
      <tns:interfaceEntry>
        <tns:port>33</tns:port>
      </tns:interfaceEntry>
      <tns:interfaceEntry>
        <tns:port>35</tns:port>
      </tns:interfaceEntry>
      <tns:interfaceEntry>
        <tns:port>36</tns:port>
      </tns:interfaceEntry>
    </tns:node>
  </tns:switchEntry>

  <tns:switchEntry>
    <tns:node>
      <tns:nodeId>c80021f7cae400</tns:nodeId>
    </tns:node>
  </tns:switchEntry>

  <tns:switchEntry>
    <tns:node>
      <tns:nodeId>123456789ab</tns:nodeId>
      <tns:interfaceEntry>
        <tns:port>0</tns:port>
      </tns:interfaceEntry>
      <tns:interfaceEntry>
        <tns:port>1</tns:port>
      </tns:interfaceEntry>
      <tns:interfaceEntry>
        <tns:port>2</tns:port>
      </tns:interfaceEntry>
      <tns:interfaceEntry>
        <tns:port>3</tns:port>
      </tns:interfaceEntry>
      <tns:interfaceEntry>
        <tns:port>4</tns:port>
      </tns:interfaceEntry>
      <tns:interfaceEntry>
        <tns:port>5</tns:port>
      </tns:interfaceEntry>
      <tns:interfaceEntry>
        <tns:port>6</tns:port>
      </tns:interfaceEntry>
      <tns:interfaceEntry>
        <tns:port>7</tns:port>
      </tns:interfaceEntry>
      <tns:interfaceEntry>
        <tns:port>8</tns:port>
      </tns:interfaceEntry>
      <tns:interfaceEntry>
        <tns:port>9</tns:port>
      </tns:interfaceEntry>
      <tns:interfaceEntry>
        <tns:port>10</tns:port>
      </tns:interfaceEntry>
      <tns:interfaceEntry>
        <tns:port>11</tns:port>
      </tns:interfaceEntry>
      <tns:interfaceEntry>
        <tns:port>12</tns:port>
      </tns:interfaceEntry>
      <tns:interfaceEntry>
        <tns:port>13</tns:port>
      </tns:interfaceEntry>
      <tns:interfaceEntry>
        <tns:port>14</tns:port>
      </tns:interfaceEntry>
    </tns:node>
  </tns:switchEntry>

</tns:RSpec>
